// Inputs for the cross-engine conformance suite (TypeScript core and Kotlin plugin engine).
// Java and the QA pack are intentionally absent: the plugin's first release does not include them.
const f = (name, content) => ({ name, content });
const j = (v) => JSON.stringify(v);
const c = (name, left, right, options = {}) => ({ name, left, right, options });

export const cases = [
  // ---- JSON
  c('json/prd-example', f('a.json', '{\n  "timeout": 30000,\n  "retryCount": 3,\n  "enabled": true\n}'), f('b.json', '{\n  "timeout": 45000,\n  "retryCount": 5,\n  "enabled": true\n}')),
  c('json/identical', f('a.json', j({ a: [1, { b: 2 }], c: 'x' })), f('b.json', j({ a: [1, { b: 2 }], c: 'x' }))),
  c('json/add-remove-modify', f('a.json', j({ a: 1, n: { x: 1 } })), f('b.json', j({ b: 2, n: { x: 2 } }))),
  c('json/type-changes', f('a.json', j({ a: 1, o: {}, l: [1] })), f('b.json', j({ a: '1', o: [], l: { k: 1 } }))),
  c('json/array-length', f('a.json', j({ l: [1, 2, 3] })), f('b.json', j({ l: [1] }))),
  c('json/array-grow', f('a.json', j({ l: [1, 2] })), f('b.json', j({ l: [1, 2, 3] }))),
  c('json/nested-arrays-of-objects', f('a.json', j({ u: [{ id: 1, n: 'a' }, { id: 2, n: 'b' }] })), f('b.json', j({ u: [{ id: 1, n: 'a' }, { id: 2, n: 'c' }, { id: 3, n: 'd' }] }))),
  c('json/key-order-ignored', f('a.json', '{"a":1,"b":2}'), f('b.json', '{"b":2,"a":1}')),
  c('json/key-order-reported', f('a.json', '{"a":1,"b":2}'), f('b.json', '{"b":2,"a":1}'), { ignoreOrdering: false }),
  c('json/array-order-default', f('a.json', j({ t: [1, 2, 3] })), f('b.json', j({ t: [3, 1, 2] }))),
  c('json/array-order-ignored', f('a.json', j({ t: [1, 2, 3] })), f('b.json', j({ t: [3, 1, 2] })), { ignoreArrayOrder: true }),
  c('json/array-order-ignored-extra', f('a.json', j({ t: [1, 2] })), f('b.json', j({ t: [2, 1, 9] })), { ignoreArrayOrder: true }),
  c('json/array-order-objects', f('a.json', j({ t: [{ a: 1 }, { a: 2 }] })), f('b.json', j({ t: [{ a: 2 }, { a: 3 }] })), { ignoreArrayOrder: true }),
  c('json/ignore-path-object', f('a.json', j({ id: 1, meta: { ts: 1, by: 'x' }, l: [{ ts: 1 }] })), f('b.json', j({ id: 1, meta: { ts: 2, by: 'y' }, l: [{ ts: 9 }] })), { ignorePaths: ['meta'] }),
  c('json/ignore-path-star', f('a.json', j({ id: 1, meta: { ts: 1, by: 'x' }, l: [{ ts: 1 }] })), f('b.json', j({ id: 1, meta: { ts: 2, by: 'y' }, l: [{ ts: 9 }] })), { ignorePaths: ['meta.*', 'l[*].ts'] }),
  c('json/ignore-path-globstar', f('a.json', j({ id: 1, meta: { ts: 1, by: 'x' }, l: [{ ts: 1 }] })), f('b.json', j({ id: 1, meta: { ts: 2, by: 'y' }, l: [{ ts: 9 }] })), { ignorePaths: ['**.ts'] }),
  c('json/case-ws-default', f('a.json', j({ s: 'Hello  World' })), f('b.json', j({ s: 'hello world' }))),
  c('json/case-ws-ignored', f('a.json', j({ s: 'Hello  World' })), f('b.json', j({ s: 'hello world' })), { ignoreCase: true, ignoreWhitespace: true }),
  c('json/numeric-strings', f('a.json', j({ n: '30' })), f('b.json', j({ n: 30 }))),
  c('json/numeric-equality', f('a.json', j({ n: '30.0', m: 1.5 })), f('b.json', j({ n: 30, m: 1.50 })), { numericEquality: true }),
  c('json/number-forms', f('a.json', '{"a":30,"b":1e2,"c":0.10}'), f('b.json', '{"a":30.0,"b":100,"c":0.1}')),
  c('json/nulls-booleans', f('a.json', '{"a":null,"b":true,"c":false}'), f('b.json', '{"a":0,"b":false,"c":false}')),
  c('json/empty-containers', f('a.json', '{"a":{},"b":[]}'), f('b.json', '{"a":{"x":1},"b":[1]}')),
  c('json/unicode-escapes', f('a.json', '{"s":"caf\\u00e9 \\ud83d\\ude00"}'), f('b.json', '{"s":"café 😀"}')),
  c('json/special-keys', f('a.json', j({ 'a.b': 1, 'c d': 2 })), f('b.json', j({ 'a.b': 2, 'c d': 2 }))),
  c('json/root-scalar', f('a.json', '1'), f('b.json', '2')),
  c('json/root-array', f('a.json', '[1,2]'), f('b.json', '[1,3]')),
  c('json/long-value-truncation', f('a.json', j({ k: 'x'.repeat(100) })), f('b.json', j({ k: 'y'.repeat(100) }))),
  c('json/object-value-display', f('a.json', j({ o: { a: 1 } })), f('b.json', j({ o: { a: 1, b: [1, 'two', null] } }))),
  c('json/impact-keywords', f('a.json', j({ timeout: 30, baseUrl: 'a', title: 'x', apiKey: '1', same: 1 })), f('b.json', j({ timeout: 45, baseUrl: 'b', title: 'y', apiKey: '2', same: 1 }))),
  c('json/impact-added-removed', f('a.json', j({ password: 'p', port: 1 })), f('b.json', j({ token: 't', port: 1 }))),
  c('json/invalid-fallback', f('a.json', '{oops'), f('b.json', '{}')),
  c('json/invalid-right', f('a.json', '{"a":1}'), f('b.json', '{"a":1,}')),
  c('json/bom', f('a.json', '\uFEFF{"a":1}'), f('b.json', '{"a":2}')),

  c('json/bom-both', f('a.json', '\uFEFF{"a":1}'), f('b.json', '\uFEFF{"a":1}')),

  // ---- YAML
  c('yaml/prd-example', f('a.yaml', 'timeout: 30\nretries: 3\n'), f('b.yaml', 'timeout: 45\nretries: 5\n')),
  c('yaml/comments-order', f('a.yaml', '# c\na: 1\nb: [1, 2]\n'), f('b.yaml', 'b:\n  - 1\n  - 2\na: 1 # note\n')),
  c('yaml/anchors-merge', f('a.yaml', 'base: &b {x: 1}\nsvc:\n  <<: *b\n  y: 2\n'), f('b.yaml', 'base: {x: 1}\nsvc: {x: 9, y: 2}\n')),
  c('yaml/anchors-merge-equal', f('a.yaml', 'base: &b {x: 1}\nsvc:\n  <<: *b\n  y: 2\n'), f('b.yaml', 'base: {x: 1}\nsvc: {x: 1, y: 2}\n')),
  c('yaml/multi-document', f('a.yaml', 'a: 1\n---\nb: 2\n'), f('b.yaml', 'a: 1\n---\nb: 3\n')),
  c('yaml/lists', f('a.yaml', 's:\n  - {n: a}\n  - {n: b}\n'), f('b.yaml', 's:\n  - {n: a}\n')),
  c('yaml/array-order-ignored', f('a.yaml', 't: [1,2]\n'), f('b.yaml', 't: [2,1]\n'), { ignoreArrayOrder: true }),
  c('yaml/ignore-path', f('a.yaml', 'a: 1\nts: 5\n'), f('b.yaml', 'a: 1\nts: 6\n'), { ignorePaths: ['ts'] }),
  c('yaml/empty-docs', f('a.yaml', ''), f('b.yaml', '# only a comment\n')),
  c('yaml/scalar-types', f('a.yaml', 'a: 1\nb: "1"\nc: true\nd: null\ne: 1.5\n'), f('b.yaml', 'a: "1"\nb: 1\nc: "true"\nd: ~\ne: 1.50\n')),
  c('yaml/yes-no-strings', f('a.yaml', 'a: yes\nb: no\n'), f('b.yaml', 'a: true\nb: no\n')),
  c('yaml/multiline-strings', f('a.yaml', 'm: |\n  line1\n  line2\n'), f('b.yaml', 'm: |\n  line1\n  lineX\n')),
  c('yaml/nested', f('a.yml', 'a:\n  b:\n    c: 1\n  d: [1, {e: 2}]\n'), f('b.yml', 'a:\n  b:\n    c: 2\n  d: [1, {e: 3}, 4]\n')),
  c('yaml/impact', f('a.yaml', 'timeout: 30\nhost: a\n'), f('b.yaml', 'timeout: 45\nhost: b\n')),
  c('yaml/bom', f('a.yaml', '\uFEFFa: 1\n'), f('b.yaml', 'a: 2\n')),
  c('yaml/invalid-fallback', f('a.yaml', 'a: [1, 2\n'), f('b.yaml', 'a: 1\n')),

  // ---- XML
  c('xml/prd-example', f('a.xml', '<user>\n    <name>John</name>\n    <age>30</age>\n</user>\n'), f('b.xml', '<user>\n    <name>John</name>\n    <age>31</age>\n</user>\n')),
  c('xml/indent-comments', f('a.xml', '<a><b>1</b></a>'), f('b.xml', '<a>\n  <!-- hi -->\n  <b>1</b>\n</a>')),
  c('xml/attributes', f('a.xml', '<a x="1"/>'), f('b.xml', '<a x="2" z="3"/>')),
  c('xml/attribute-order', f('a.xml', '<a x="1" y="2"/>'), f('b.xml', '<a y="2" x="1"/>')),
  c('xml/repeated', f('a.xml', '<l><i>1</i><i>2</i></l>'), f('b.xml', '<l><i>1</i><i>3</i><i>4</i></l>')),
  c('xml/repeated-unordered', f('a.xml', '<l><i>1</i><i>2</i></l>'), f('b.xml', '<l><i>2</i><i>1</i></l>'), { ignoreArrayOrder: true }),
  c('xml/added-removed', f('a.xml', '<a><b/><c/></a>'), f('b.xml', '<a><b/><d/></a>')),
  c('xml/mixed-content', f('a.xml', '<a k="1">hi</a>'), f('b.xml', '<a k="1">bye</a>')),
  c('xml/cdata', f('a.xml', '<a><![CDATA[x<y]]></a>'), f('b.xml', '<a>x&lt;y</a>')),
  c('xml/entities', f('a.xml', '<a>Tom &amp; Jerry &#65;</a>'), f('b.xml', '<a>Tom &amp; Jerry A</a>')),
  c('xml/ignore-attributes', f('a.xml', '<a id="1" v="x"/>'), f('b.xml', '<a id="2" v="x"/>'), { ignoreAttributes: ['id'] }),
  c('xml/namespaces-default', f('a.xml', '<r xmlns:p="u"><p:i>1</p:i></r>'), f('b.xml', '<r xmlns:q="u"><q:i>1</q:i></r>')),
  c('xml/namespaces-ignored', f('a.xml', '<r xmlns:p="u"><p:i>1</p:i></r>'), f('b.xml', '<r xmlns:q="u"><q:i>1</q:i></r>'), { ignoreNamespaces: true }),
  c('xml/declaration-compared', f('a.xml', '<?xml version="1.0" encoding="UTF-8"?><a/>'), f('b.xml', '<a/>')),
  c('xml/declaration-ignored', f('a.xml', '<?xml version="1.0" encoding="UTF-8"?><a/>'), f('b.xml', '<a/>'), { ignoreXmlDeclaration: true }),
  c('xml/whitespace-text', f('a.xml', '<a>x  y</a>'), f('b.xml', '<a>x y</a>')),
  c('xml/whitespace-ignored', f('a.xml', '<a>x  y</a>'), f('b.xml', '<a>x y</a>'), { ignoreWhitespace: true }),
  c('xml/empty-vs-text', f('a.xml', '<a><b/></a>'), f('b.xml', '<a><b>t</b></a>')),
  c('xml/nested-attrs-and-text', f('a.xml', '<a><b k="1">t</b><c/></a>'), f('b.xml', '<a><b k="2">u</b><c/></a>')),
  c('xml/impact', f('a.xml', '<cfg><timeout>30</timeout><host>a</host></cfg>'), f('b.xml', '<cfg><timeout>45</timeout><host>b</host></cfg>')),
  c('xml/bom', f('a.xml', '\uFEFF<a>1</a>'), f('b.xml', '<a>2</a>')),
  c('xml/numeric-char-refs', f('a.xml', '<a k="&#65;">&#x42;&#67;</a>'), f('b.xml', '<a k="A">BC</a>')),
  c('xml/malformed-fallback', f('a.xml', '<a><b></a>'), f('b.xml', '<a/>')),

  // ---- Text (and unknown extensions)
  c('text/one-line-modified', f('a.txt', 'hello\nworld\n'), f('b.txt', 'hello\nthere\n')),
  c('text/identical-empty', f('a.txt', ''), f('b.txt', '')),
  c('text/trailing-newline', f('a.txt', 'a\nb'), f('b.txt', 'a\nb\n')),
  c('text/add-remove', f('a.txt', 'a\nb\nc\n'), f('b.txt', 'a\nc\nd\n')),
  c('text/crlf', f('a.txt', 'a\r\nb\r\n'), f('b.txt', 'a\nb\n')),
  c('text/ignore-ws', f('a.txt', 'a  b\n'), f('b.txt', ' a b \n'), { ignoreWhitespace: true }),
  c('text/ignore-case', f('a.txt', 'Hello\n'), f('b.txt', 'hello\n'), { ignoreCase: true }),
  c('text/markdown-ext', f('a.md', '# a\n'), f('b.md', '# b\n')),
  c('text/many-edits', f('a.txt', Array.from({ length: 60 }, (_, i) => `line ${i}`).join('\n')), f('b.txt', Array.from({ length: 60 }, (_, i) => (i % 7 === 0 ? `LINE ${i}` : i === 30 ? '' : `line ${i}`)).filter((_, i) => i !== 31).join('\n'))),
  c('text/reordered-blocks', f('a.txt', 'a\nb\nc\nd\ne\n'), f('b.txt', 'd\ne\na\nb\nc\n')),
  c('text/forced-format-json-as-text', f('a.json', '{"a":1}'), f('b.json', '{"a":2}'), { format: 'text' }),
  c('text/blank-lines', f('a.txt', '\n\na\n\n'), f('b.txt', '\na\n\n\n')),

  // ---- API responses (expected = left, actual = right)
  c('api/prd-example', f('expected.json', j({ status: 200, body: { user: { id: 123, name: 'John' }, amount: 100, currency: 'INR' } })), f('actual.json', j({ status: 200, body: { user: { id: 123, name: 'John' }, amount: 120, currency: 'INR' } })), { format: 'api' }),
  c('api/pass', f('e.json', j({ status: 200, headers: { 'Content-Type': 'application/json', Date: 'x' }, body: { a: 1 } })), f('a.json', j({ status: 200, headers: { 'content-type': 'application/json', date: 'y', 'X-Extra': '1' }, body: { a: 1 } })), { format: 'api' }),
  c('api/status-and-headers', f('e.json', j({ status: 200, headers: { 'content-type': 'a' }, body: {} })), f('a.json', j({ status: 500, headers: { 'content-type': 'b' }, body: {} })), { format: 'api' }),
  c('api/missing-header', f('e.json', j({ status: 200, headers: { 'x-a': '1' }, body: {} })), f('a.json', j({ status: 200, headers: {}, body: {} })), { format: 'api' }),
  c('api/missing-and-extra-fields', f('e.json', j({ status: 200, body: { user: { id: 123, name: 'John' }, amount: 100, currency: 'INR' } })), f('a.json', j({ status: 200, body: { user: { id: 123 }, amount: 100, extra: true } })), { format: 'api' }),
  c('api/ignore-extra', f('e.json', j({ status: 200, body: { user: { id: 123, name: 'John' }, amount: 100, currency: 'INR' } })), f('a.json', j({ status: 200, body: { user: { id: 123 }, amount: 100, extra: true } })), { format: 'api', ignoreExtraFields: true }),
  c('api/ignore-extra-and-paths', f('e.json', j({ status: 200, body: { user: { id: 123, name: 'John' }, amount: 100, currency: 'INR' } })), f('a.json', j({ status: 200, body: { user: { id: 123 }, amount: 100, extra: true } })), { format: 'api', ignoreExtraFields: true, ignorePaths: ['currency', 'user.name'] }),
  c('api/ignore-headers', f('e.json', j({ status: 200, headers: { 'x-a': '1', 'x-b': '2' }, body: {} })), f('a.json', j({ status: 200, headers: { 'x-a': '9', 'x-b': '2' }, body: {} })), { format: 'api', ignoreHeaders: ['X-A'] }),
  c('api/bodies-only', f('e.json', '{"ids":[1,2]}'), f('a.json', '{"ids":[2,1]}'), { format: 'api' }),
  c('api/bodies-only-unordered', f('e.json', '{"ids":[1,2]}'), f('a.json', '{"ids":[2,1]}'), { format: 'api', ignoreArrayOrder: true }),
  c('api/raw-http', f('e.http', 'HTTP/1.1 201 Created\r\nContent-Type: application/json\r\nX-A: 1\r\n\r\n{"id":5}'), f('a.http', 'HTTP/1.1 201 Created\r\ncontent-type: application/json\r\nX-A: 2\r\n\r\n{"id":6}'), { format: 'api' }),
  c('api/raw-http-no-headers', f('e.txt', 'HTTP/1.1 200 OK\n\nhello'), f('a.txt', 'HTTP/1.1 200 OK\n\nbye'), { format: 'api' }),
  c('api/raw-http-vs-envelope', f('e.txt', 'HTTP/1.1 200 OK\nContent-Type: text/plain\n\n{"a":1}'), f('a.json', j({ statusCode: 200, headers: { 'Content-Type': 'text/plain' }, body: '{"a":1}' })), { format: 'api' }),
  c('api/status-one-side', f('e.json', j({ status: 200, body: { a: 1 } })), f('a.json', '{"a":1}'), { format: 'api' }),
  c('api/envelope-data-key', f('e.json', j({ status: 200, data: { a: 1 } })), f('a.json', j({ status: 200, data: { a: 2 } })), { format: 'api' }),
  c('api/text-bodies', f('e.txt', 'plain text'), f('a.txt', 'plain text!'), { format: 'api' }),
  c('api/string-status-not-envelope', f('e.json', '{"status":"ok","data":1}'), f('a.json', '{"status":"ok","data":2}'), { format: 'api' }),
  c('api/many-mismatches', f('e.json', '{"a":1,"b":1}'), f('a.json', '{"a":2,"b":2}'), { format: 'api' }),
];
